Vagrant.configure("2") do |config|
  config.vm.define "ansible_t" do |ansible|
    
    # OS
    ansible.vm.box = "ubuntu/bionic64"
    
    # Network configuration
    ansible.vm.network "private_network", ip: "192.168.33.10"
    ansible.vm.network "forwarded_port", guest: 22, host: 2223

    # Hostname
    ansible.vm.hostname = "ansible-controller"
  end
end


